kind = "api"
previewPath = "/"
title = "Job Scout Agent"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "API Server"
paths = ["/"]

[services.development]
run = "PORT=8080 npm run dev"

[services.production]
build = "pnpm --filter @workspace/api-server run build"
run = "PORT=8080 pnpm --filter @workspace/api-server run start"

[services.production.health.startup]
path = "/api/healthz"
